In [1]:
import rpy2.robjects as robjects
r = robjects.r
r.source('ml_fan_pipe.R')

wkly_plyr_stats_r = robjects.globalenv['wkly_plyr_stats']

In [2]:
wkly_plyr_stats_r(2020)

<rpy2.rinterface_lib.sexp.NULLType object at 0x7fe4b03b87c0> [RTYPES.NILSXP]

In [4]:
import pandas as pd
# def data_processing(file_name):
#     """
#     Read the csv files and create game characterstic features and player statistic features
#     """
    
df = pd.read_csv('data/wkly_plyr_stats_2020.csv')
print(df.columns)
df.head()

Index(['player_id', 'player_name', 'recent_team', 'season', 'week',
       'season_type', 'completions', 'attempts', 'passing_yards',
       'passing_tds', 'interceptions', 'sacks', 'sack_yards', 'sack_fumbles',
       'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch',
       'passing_first_downs', 'passing_epa', 'passing_2pt_conversions', 'pacr',
       'dakota', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles',
       'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa',
       'rushing_2pt_conversions', 'receptions', 'targets', 'receiving_yards',
       'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost',
       'receiving_air_yards', 'receiving_yards_after_catch',
       'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions',
       'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds',
       'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

,player_id,player_name,recent_team,season,week,season_type,completions,attempts,passing_yards,passing_tds,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
0,00-0019596,T.Brady,TB,2020,1,REG,23,36,239,2,...,0,NaN,0,NaN,NaN,NaN,NaN,0,20.46,20.46
1,00-0019596,T.Brady,TB,2020,2,REG,23,35,217,1,...,0,NaN,0,NaN,NaN,NaN,NaN,0,8.68,8.68
2,00-0019596,T.Brady,TB,2020,3,REG,25,38,297,3,...,0,NaN,0,NaN,NaN,NaN,NaN,0,23.88,23.88
3,00-0019596,T.Brady,TB,2020,4,REG,30,46,369,5,...,0,NaN,0,NaN,NaN,NaN,NaN,0,32.46,32.46
4,00-0019596,T.Brady,TB,2020,5,REG,25,41,253,1,...,0,NaN,0,NaN,NaN,NaN,NaN,0,14.12,14.12

In [6]:
df.sort_values(by = ['player_id', 'week']).head() # for rolling average

,player_id,player_name,recent_team,season,week,season_type,completions,attempts,passing_yards,passing_tds,...,receiving_first_downs,receiving_epa,receiving_2pt_conversions,racr,target_share,air_yards_share,wopr,special_teams_tds,fantasy_points,fantasy_points_ppr
0,00-0019596,T.Brady,TB,2020,1,REG,23,36,239,2,...,0,NaN,0,NaN,NaN,NaN,NaN,0,20.46,20.46
1,00-0019596,T.Brady,TB,2020,2,REG,23,35,217,1,...,0,NaN,0,NaN,NaN,NaN,NaN,0,8.68,8.68
2,00-0019596,T.Brady,TB,2020,3,REG,25,38,297,3,...,0,NaN,0,NaN,NaN,NaN,NaN,0,23.88,23.88
3,00-0019596,T.Brady,TB,2020,4,REG,30,46,369,5,...,0,NaN,0,NaN,NaN,NaN,NaN,0,32.46,32.46
4,00-0019596,T.Brady,TB,2020,5,REG,25,41,253,1,...,0,NaN,0,NaN,NaN,NaN,NaN,0,14.12,14.12

In [9]:
# All box score player stats, except defensive statistics
stats = df.columns[6:]

Index(['completions', 'attempts', 'passing_yards', 'passing_tds',
       'interceptions', 'sacks', 'sack_yards', 'sack_fumbles',
       'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch',
       'passing_first_downs', 'passing_epa', 'passing_2pt_conversions', 'pacr',
       'dakota', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles',
       'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa',
       'rushing_2pt_conversions', 'receptions', 'targets', 'receiving_yards',
       'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost',
       'receiving_air_yards', 'receiving_yards_after_catch',
       'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions',
       'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds',
       'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

In [10]:
#     # Game Characteristic Indicators, e.g. home/away, opponent, team
#     df, game_features = get_game_char_indicators(df)
#     # Player Statistic Features, e.g. Season, last 4 weeks, previous week
#     df, player_features = get_player_averages(df, stats)
#     features = game_features + player_features
#     df = df.fillna(0)
#     return df, features