In [1]:
import pandas as pd
import numpy as np

base = "https://raw.githubusercontent.com/"
url_agg = "zzhangusf/Predicting-Fantasy-Football-Points-Using-Machine-Learning/master/data/aggregated_2015.csv"
df_agg = pd.read_csv(base+url_agg)
#df_agg.columns

url_box = "zzhangusf/Predicting-Fantasy-Football-Points-Using-Machine-Learning/master/data/players_box_scores_2015.csv"
df_box = pd.read_csv(base+url_box)
#df_box.shape

## Normalizing Names

In [2]:
names_df = pd.read_csv('data/all_nfl_team_abbr.csv')
names_df.head(3)

,TeamName,fanduel_2015,statistics_2015,fantasy_2015,fanduel_2016,statistics_2016,fantasy_2016
0,Arizona Cardinals,ari,ARI,ARI,ari,ARI,ARI
1,Atlanta Falcons,atl,ATL,ATL,atl,ATL,ATL
2,Baltimore Ravens,bal,BAL,BAL,bal,BAL,BAL

?pd.DataFrame.reset_index

In [3]:
names_df.replace({"Oakland Raiders": "Las Vegas Raiders", \
                  "San Diego Chargers": "Los Angeles Chargers", \
                 "St.Louis / Los Angeles Rams": "Los Angeles Rams"}, inplace=True)

names_df.sort_values('TeamName', inplace=True)
names_df.drop(names_df.columns[1:], axis=1, inplace=True)
names_df1 = names_df.reset_index(drop=True)
#names_df1

In [4]:
def get_unique_team_names(df, col):
    temp_df = pd.read_csv(df) 
    temp_list = list(temp_df[col].unique())
    temp_list.sort()
    return temp_list

In [5]:
import glob

temp_lists=[]
temp_cols=[]
for file in glob.glob('data/202*_Fanduel_Results.csv'):
    temp_list = get_unique_team_names(file, 'Team')
    temp_col = file
    temp_cols.append(temp_col)
    temp_lists.append(temp_list)

In [6]:
print(temp_lists, temp_cols)

[['ari', 'atl', 'bal', 'buf', 'car', 'chi', 'cin', 'cle', 'dal', 'den', 'det', 'gnb', 'hou', 'ind', 'jac', 'kan', 'lac', 'lar', 'lvr', 'mia', 'min', 'nor', 'nwe', 'nyg', 'nyj', 'phi', 'pit', 'sea', 'sfo', 'tam', 'ten', 'was'], ['ari', 'atl', 'bal', 'buf', 'car', 'chi', 'cin', 'cle', 'dal', 'den', 'det', 'gnb', 'hou', 'ind', 'jac', 'kan', 'lac', 'lar', 'lvr', 'mia', 'min', 'nor', 'nwe', 'nyg', 'nyj', 'phi', 'pit', 'sea', 'sfo', 'tam', 'ten', 'was']] ['data/2020_Fanduel_Results.csv', 'data/2021_Fanduel_Results.csv']

In [7]:
names_df2 = pd.DataFrame(temp_lists).T
temp_cols_short = [i[5:17] for i in temp_cols]
names_df2.columns = temp_cols_short
#names_df2

In [8]:
wk_temp = pd.read_csv('data/wkly_plyr_stats_2020.csv')
#wk_temp.columns

In [9]:
team_list = list(wk_temp.recent_team.unique())
team_list.sort()
print(team_list)

['ARI', 'ATL', 'BAL', 'BUF', 'CAR', 'CHI', 'CIN', 'CLE', 'DAL', 'DEN', 'DET', 'GB', 'HOU', 'IND', 'JAX', 'KC', 'LA', 'LAC', 'LV', 'MIA', 'MIN', 'NE', 'NO', 'NYG', 'NYJ', 'PHI', 'PIT', 'SEA', 'SF', 'TB', 'TEN', 'WAS']

In [10]:
names_df = pd.concat([names_df1, names_df2], axis=1)
names_df['2020_stats'] = team_list
names_df.head(3)

                TeamName 2020_Fanduel 2021_Fanduel 2020_stats
0      Arizona Cardinals          ari          ari        ARI
1        Atlanta Falcons          atl          atl        ATL
2       Baltimore Ravens          bal          bal        BAL
3          Buffalo Bills          buf          buf        BUF
4      Carolina Panthers          car          car        CAR
5          Chicago Bears          chi          chi        CHI
6     Cincinnati Bengals          cin          cin        CIN
7       Cleveland Browns          cle          cle        CLE
8         Dallas Cowboys          dal          dal        DAL
9         Denver Broncos          den          den        DEN
10         Detroit Lions          det          det        DET
11     Green Bay Packers          gnb          gnb         GB
12        Houston Texans          hou          hou        HOU
13    Indianapolis Colts          ind          ind        IND
14  Jacksonville Jaguars          jac          jac        JAX
15    Kansas City Chiefs          kan          kan         KC
16     Las Vegas Raiders          lac          lac         LA
17  Los Angeles Chargers          lar          lar        LAC
18      Los Angeles Rams          lvr          lvr         LV
19        Miami Dolphins          mia          mia        MIA
20     Minnesota Vikings          min          min        MIN
21  New England Patriots          nor          nor         NE
22     New Orlean Saints          nwe          nwe         NO
23       New York Giants          nyg          nyg        NYG
24         New York Jets          nyj          nyj        NYJ
25   Philadelphia Eagles          phi          phi        PHI
26   Pittsburgh Steelers          pit          pit        PIT
27   San Francisco 49ers          sea          sea        SEA
28      Seattle Seahawks          sfo          sfo         SF
29  Tampa Bay Buccaneers          tam          tam         TB
30      Tennessee Titans          ten          ten        TEN
31   Washington Redskins          was          was        WAS

?pd.concat

In [11]:
wk_temp = pd.read_csv('data/wkly_plyr_stats_2021.csv')
#wk_temp.columns

In [12]:
team_list = list(wk_temp.recent_team.unique())
team_list.sort()
print(team_list)

['ARI', 'ATL', 'BAL', 'BUF', 'CAR', 'CHI', 'CIN', 'CLE', 'DAL', 'DEN', 'DET', 'GB', 'HOU', 'IND', 'JAX', 'KC', 'LA', 'LAC', 'LV', 'MIA', 'MIN', 'NE', 'NO', 'NYG', 'NYJ', 'PHI', 'PIT', 'SEA', 'SF', 'TB', 'TEN', 'WAS']

In [13]:
names_df['2021_stats'] = team_list
names_df

                TeamName 2020_Fanduel 2021_Fanduel 2020_stats 2021_stats
0      Arizona Cardinals          ari          ari        ARI        ARI
1        Atlanta Falcons          atl          atl        ATL        ATL
2       Baltimore Ravens          bal          bal        BAL        BAL
3          Buffalo Bills          buf          buf        BUF        BUF
4      Carolina Panthers          car          car        CAR        CAR
5          Chicago Bears          chi          chi        CHI        CHI
6     Cincinnati Bengals          cin          cin        CIN        CIN
7       Cleveland Browns          cle          cle        CLE        CLE
8         Dallas Cowboys          dal          dal        DAL        DAL
9         Denver Broncos          den          den        DEN        DEN
10         Detroit Lions          det          det        DET        DET
11     Green Bay Packers          gnb          gnb         GB         GB
12        Houston Texans          hou          hou        HOU        HOU
13    Indianapolis Colts          ind          ind        IND        IND
14  Jacksonville Jaguars          jac          jac        JAX        JAX
15    Kansas City Chiefs          kan          kan         KC         KC
16     Las Vegas Raiders          lac          lac         LA         LA
17  Los Angeles Chargers          lar          lar        LAC        LAC
18      Los Angeles Rams          lvr          lvr         LV         LV
19        Miami Dolphins          mia          mia        MIA        MIA
20     Minnesota Vikings          min          min        MIN        MIN
21  New England Patriots          nor          nor         NE         NE
22     New Orlean Saints          nwe          nwe         NO         NO
23       New York Giants          nyg          nyg        NYG        NYG
24         New York Jets          nyj          nyj        NYJ        NYJ
25   Philadelphia Eagles          phi          phi        PHI        PHI
26   Pittsburgh Steelers          pit          pit        PIT        PIT
27   San Francisco 49ers          sea          sea        SEA        SEA
28      Seattle Seahawks          sfo          sfo         SF         SF
29  Tampa Bay Buccaneers          tam          tam         TB         TB
30      Tennessee Titans          ten          ten        TEN        TEN
31   Washington Redskins          was          was        WAS        WAS

In [14]:
names_df.to_csv('data/all_nfl_team_abbr_2021.csv')